version: 2
jobs:
  build:
    environment:
      - PROJECT_ID: skyhitz-161021
      - REPOSITORY_ID: github_alejomendoza_api
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: Export google service key
          command: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
      - run:
          name: Authenticate google cloud
          command: gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
      - run:
          name: Set google cloud project
          command: gcloud config set project $PROJECT_ID
      - run:
          name: Deploy api
          command: gcloud beta functions deploy $CIRCLE_BRANCH-api --source https://source.developers.google.com/projects/$PROJECT_ID/repos/$REPOSITORY_ID/moveable-aliases/$CIRCLE_BRANCH --trigger-http --entry-point graphql --memory 2048MB --set-env-vars ALGOLIA_APP_ID=$ALGOLIA_APP_ID,ALGOLIA_ADMIN_API_KEY=$ALGOLIA_ADMIN_API_KEY,API_ENDPOINT=$API_ENDPOINT,DATA_BACKEND=$DATA_BACKEND,DATABASE=$DATABASE,ENV=$ENV,DB_USER=$DB_USER,PASSWORD=$PASSWORD,INSTANCE_CONNECTION_NAME=$INSTANCE_CONNECTION_NAME,HOST=$HOST,JWT_SECRET=$JWT_SECRET,SENDGRID_API_KEY=$SENDGRID_API_KEY,UNIVERSAL_LINK_SCHEME=$UNIVERSAL_LINK_SCHEME,HORIZON_URL=$HORIZON_URL,STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY,STRIPE_CONNECT_CLIENT_ID=$STRIPE_CONNECT_CLIENT_ID,STRIPE_PLAN_ID=$STRIPE_PLAN_ID,ISSUER_ID=$ISSUER_ID,ISSUER_SEED=$ISSUER_SEED --verbosity debug
workflows:
  version: 2
  build-staging-context:
    jobs:
      - build:
          context: staging
          filters:
            branches:
              only:
                - staging
  build-master-context:
    jobs:
      - build:
          context: master
          filters:
            branches:
              only:
                - master
